{% set name = "dpu-utils" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/dpu_utils-{{ version }}.tar.gz
  sha256: b970fc4b748910209af79c9b75fded33dae9737a069220f2fe3ef951d6aebc64

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - azure-identity
    - azure-storage-blob
    - chardet
    - idna
    - isodate
    - msal
    - msrest
    - oauthlib
    - portalocker ~=1.0
    - pycparser
    - cryptography
    - cffi
    - docopt
    - numpy
    - python >=3.6
    - regex
    - sentencepiece ==0.1.92
    - setsimilaritysearch
    - tqdm
    - requests
    - urllib3

test:
  imports:
    - dpu_utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/dpu-utils
  summary: Python utilities used by Deep Procedural Intelligence
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
